#!/usr/bin/env python
# This file is part of ctrl_filterd
#
# Developed for the LSST Data Management System.
# This product includes software developed by the LSST Project
# (https://www.lsst.org).
# See the COPYRIGHT file at the top-level directory of this distribution
# for details of code ownership.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import logging
import os

import lsst.log as lsstlog
from lsst.ctrl.filterd.filterd import FilterD

lsstlog.usePythonLogging()

log_level_name = "INFO"
filterd_log_var = "CTRL_FILTERD_LOG_LEVEL"

if filterd_log_var in os.environ:
    log_level_name = os.environ[filterd_log_var]

level_mapping = logging.getLevelNamesMapping()
log_level = level_mapping.get(log_level_name, logging.INFO)

LOGGER = logging.getLogger(__name__)
F = "%(levelname) -10s %(asctime)s.%(msecs)03dZ %(name) -30s %(funcName) -35s %(lineno) -5d: %(message)s"
logging.basicConfig(level=log_level, format=F, datefmt="%Y-%m-%d %H:%M:%S")


if __name__ == "__main__":
    LOGGER.info("log level = %s", log_level_name)
    filterd = FilterD()
    filterd.run()
